# Generated by Django 3.2.18 on 2023-04-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='total',
            field=models.IntegerField(default=3),
        ),
    ]
