# Generated by Django 3.2.18 on 2023-04-14 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rooms_showed'),
    ]

    operations = [
        migrations.CreateModel(
            name='InGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=3)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('msg', models.CharField(default='', max_length=35)),
                ('iusers', models.ManyToManyField(related_name='iusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
