# Generated by Django 3.2.18 on 2023-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ingame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='showed',
        ),
        migrations.AddField(
            model_name='rooms',
            name='gameJson',
            field=models.JSONField(default={'status': 'waiting'}),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='InGame',
        ),
    ]
