# Generated by Django 3.2.18 on 2023-04-22 11:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230422_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='gameJson',
            field=models.JSONField(default=app.models.defaultGameJSON),
        ),
    ]
