# Generated by Django 3.2.18 on 2023-04-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_rooms_lobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='total',
            new_name='capacity',
        ),
    ]
