# Generated by Django 3.2.18 on 2023-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_total_lobby_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
    ]
